### PR TITLE
Use the latest thunderbird icon

### PR DESCRIPTION
**Pull request by soumyaDghosh**
I think, this can be used in the stable branch also.

### CODE REVIEW

**Comment by fenris** [comment]
any update on this?

**Review by seb128 — CHANGES_REQUESTED** [review]
Thank you for the suggested change, could you specify where the icon is coming from and also maybe squash the 3 commits in one?

**Comment by fenris** [comment]
can we use the logo from here: 

https://github.com/thundernest/design-docs/blob/b118bb31ca7f46c93d359862478b71cd722873f0/.gitbook/assets/Thunderbird_Logo.png

**Comment by soumyaDghosh** [comment]
@seb128 I actually got the icon from the snap itself(latest/stable)

image

**Review by seb128 — APPROVED** [review]
Thanks!

**Comment by fenris** [comment]
is it possible to do a symbolic link for the thunderbird.png 

snap/gui/thunderbird.png -> /snap/thunderbird/current/snap/gui/default256.png ? 

if we using the beta channel, the icon still uses the stable whereby there is a beta word at the icon if we are using the beta channel.

**Pull request merged**
