### PR TITLE
snap: add some metadatas like title and links

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by hellsworth** [comment]
Thanks Soumya! Just a request to change the bug filing link for the thunderbird snap, otherwise lgtm!

**Comment by soumyaDghosh** [comment]
Hi @hellsworth thanks for your suggestion. What link should I point to, for bug filling

**Comment by hellsworth** [comment]
> Hi @hellsworth thanks for your suggestion. What link should I point to, for bug filling

the link I provided:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird&op_sys=Linux&keywords=snap

This link will start a new issue with a few key things pre-populated.

**Comment by soumyaDghosh** [comment]
Done!

**Comment by hellsworth** [comment]
LGTM! I don't have perms to merge so @seb128 does this look ok and could you please merge?

**Review by seb128 — APPROVED** [review]
Thanks

**Comment by seb128** [comment]
in fact it has conflicts, could you rebase it first?

**Comment by soumyaDghosh** [comment]
Done! :tada:

**Pull request merged**
